--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 03. 16. 15:13:41
-- Server version: 5.5.5-10.4.27-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'latin1';

--
-- Set default database
--
USE focistak;

--
-- Drop procedure `GenRandom`
--
DROP PROCEDURE IF EXISTS GenRandom;

--
-- Drop table `focistak`
--
DROP TABLE IF EXISTS focistak;

--
-- Drop table `csapatok`
--
DROP TABLE IF EXISTS csapatok;

--
-- Drop table `posztok`
--
DROP TABLE IF EXISTS posztok;

--
-- Set default database
--
USE focistak;

--
-- Create table `posztok`
--
CREATE TABLE posztok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  posztId INT(11) DEFAULT NULL,
  posztNev VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `FK_posztok_focistak_id` on table `posztok`
--
ALTER TABLE posztok 
  ADD INDEX FK_posztok_focistak_id(id);

--
-- Create table `csapatok`
--
CREATE TABLE csapatok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  csapatId INT(11) DEFAULT NULL,
  csapatNev VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 4681,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `focistak`
--
CREATE TABLE focistak (
  id INT(11) NOT NULL AUTO_INCREMENT,
  focistaNev VARCHAR(255) DEFAULT NULL,
  posztId INT(11) DEFAULT NULL,
  csapatId INT(11) DEFAULT NULL,
  posztNev VARCHAR(255) DEFAULT NULL,
  csapatNev VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE focistak 
  ADD CONSTRAINT FK_focistak_csapatok_id FOREIGN KEY (csapatId)
    REFERENCES csapatok(id);

--
-- Create foreign key
--
ALTER TABLE focistak 
  ADD CONSTRAINT FK_focistak_posztok_id FOREIGN KEY (posztId)
    REFERENCES posztok(id);

DELIMITER $$

--
-- Create procedure `GenRandom`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE GenRandom()
BEGIN
#delete
DELETE
  FROM focistak;
DELETE
  FROM csapatok;
DELETE
  FROM posztok;





INSERT INTO posztok (id, posztId, posztNev)
  VALUES (1, 1, 'kozepPalyas'),
  (2, 1, 'csatar'),
  (3, 2, 'vedo'),
  (4, 3, 'kapus');

INSERT INTO csapatok (id, csapatId, csapatNev)
  VALUES (1, 7, 'arsenal'), (2, 6, 'Manchester City FC'), (3, 5, 'Manchester United FC'), (4, 4, 'Tottenham Hotspur FC'), (5, 3, 'Newcastle United FC'), (6, 2, 'FC Barcelona'), (7, 1, 'Real Madrid');

# insert the focistak
INSERT INTO focistak (id, focistaNev, posztId, csapatId, posztNev, csapatNev)
  VALUES (1, 'Xhaka, Granit', 2, 7, 'középPályás', 'arsenal'), (2, 'De Bruyne Kevin', 2, 3, 'középPályás', 'Manchester City FC'), (3, 'Phil Jones', 3, 3, 'vedo', 'Manchester United FC'),
  (4, 'Perisic Ivan', 1, 4, 'Tottenham Hotspur FC', 'csatar'),
  (5, 'Dubravka, Martin', 4, 5, 'Newcastle United FC', 'kapus'),
  (6, 'Lewandowski, Robert', 2, 6, 'FC Barcelona', 'csatar'), (7, 'Benzema Karim', 2, 7, 'Real Madrid', 'csatar');


#Selects
SELECT
  *
FROM csapatok;
SELECT
  *
FROM focistak;
SELECT
  *
FROM posztok;


END
$$

DELIMITER ;

-- 
-- Dumping data for table posztok
--
INSERT INTO posztok VALUES
(1, 1, 'kozepPalyas'),
(2, 1, 'csatar'),
(3, 2, 'vedo'),
(4, 3, 'kapus');

-- 
-- Dumping data for table csapatok
--
INSERT INTO csapatok VALUES
(1, 7, 'arsenal'),
(2, 6, 'Manchester City FC'),
(3, 5, 'Manchester United FC'),
(4, 4, 'Tottenham Hotspur FC'),
(5, 3, 'Newcastle United FC'),
(6, 2, 'FC Barcelona'),
(7, 1, 'Real Madrid');

-- 
-- Dumping data for table focistak
--
INSERT INTO focistak VALUES
(1, 'Xhaka, Granit', 2, 7, 'középPályás', 'arsenal'),
(2, 'De Bruyne Kevin', 2, 3, 'középPályás', 'Manchester City FC'),
(3, 'Phil Jones', 3, 3, 'vedo', 'Manchester United FC'),
(4, 'Perisic Ivan', 1, 4, 'Tottenham Hotspur FC', 'csatar'),
(5, 'Dubravka, Martin', 4, 5, 'Newcastle United FC', 'kapus'),
(6, 'Lewandowski, Robert', 2, 6, 'FC Barcelona', 'csatar'),
(7, 'Benzema Karim', 2, 7, 'Real Madrid', 'csatar');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;